---
title: "BetterFi"
author: "Tilina Alzaben"
date: '2022-06-21'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r, echo = FALSE}
#IMPORT LIBRARIES
library(readr)
library(ggplot2)
library(dplyr)
library(knitr)
library(lubridate)
```

```{r, echo = FALSE}
#Read in the Client and Loan Data
client <- read_csv("C:/Users/tilin/Desktop/BetterFi/Copy of DataLab-clientdata-anon.csv")
loan <- read_csv("C:/Users/tilin/Desktop/BetterFi/Copy of DataLab-loandata-anon.csv")
```

```{r}
#Cleaning Client Data
clientClean <- client %>% 
  mutate(age = year(Sys.Date()) - dob) %>%
  mutate(residenceyear= floor(as.numeric(residenceperiod)/12)) %>% 
  mutate(employer = ifelse(is.na(employer), "UNEMPLOYED", client$employer)) %>% 
  mutate(incomeamt = case_when(incomefreq == 'MO' || incomefreq == 'mo' ~ incomeamt, 
                               incomefreq == 'biwk' || incomefreq == 'BI' ~ incomeamt * 2, 
                               incomefreq == 'WE' ~ incomeamt * 4)) %>% 
  mutate(residencetype = ifelse(is.na(residencetype), 'UNKNOWN', client$residencetype)) %>% 
  select(custID,
         sex, 
         age, 
         carsinhh,
         housingexpense,
         phoneplanexpense,
         waterexpense,
         elecexpense,
         carinsexpense,
         annualincome,
         cellphone,
         streetcity,
         streetzip,
         residenceyear,
         County, 
         income_source, 
         employer, 
         referenceperson,
         incomeamt,
         incomelevel)
clientClean %>% View
```

```{r}
#Cleaning Loan Data
loanClean <- loan %>% 
  mutate(status_code = ifelse(is.na(status_code), "active", loan$status_code)) %>% 
  mutate(amountDue = payment_due_amount_cents * 0.01 ) %>% 
  select(primary_borrower_name, status_code, purpose, amount_approved, interest_rate, amountDue)
loanClean %>% View
```

```{r}
#Combining PIF and Refinanced 
adjustedLoan <- loan %>% 
  mutate(status_code = case_when(status_code == 'pif_refinanced' ~ 'pif', 
                                 is.na(status_code) ~ 'active', 
                                 TRUE ~ loan$status_code)) %>% 
  mutate(amountDue = payment_due_amount_cents * 0.01 ) %>% 
  select(primary_borrower_name, status_code, purpose, amount_approved, interest_rate, amountDue)
adjustedDf %>% View

new_df <- merge(clientClean, adjustedLoan, by.x = 'custID', by.y = 'primary_borrower_name')
new_df %>% View

new_df <- new_df[new_df$status_code != 'active',]
new_df <- new_df[new_df$incomelevel != '#N/A',]
```


```{r}
#Creating One Data set
df <- merge(clientClean, loanClean, by.x = 'custID', by.y = 'primary_borrower_name')
df %>% View

df <- df[df$status_code != 'active',]
df <- df[df$incomelevel != '#N/A',]
df %>% View
```

```{r}
#Turning Categorical Variables into Factors
df$sex <- as.factor(df$sex)
df$cellphone <- as.factor(df$cellphone)
df$streetcity <- as.factor(df$streetcity)
df$streetzip <- as.factor(df$streetzip)
df$County <- as.factor(df$County)
df$income_source <- as.factor(df$income_source)
df$employer <- as.factor(df$employer)
df$referenceperson <- as.factor(df$referenceperson)
df$incomelevel <- as.factor(df$incomelevel)
df$carsinhh <- as.factor(df$carsinhh)

df$status_code <- as.factor(df$status_code)
df$purpose <- as.factor(df$purpose)

#Dropping the 'active' Factor
df$status_code <- droplevels(df$status_code)
df$incomelevel <- droplevels(df$incomelevel)
str(df)
```

```{r}
new_df$sex <- as.factor(new_df$sex)
new_df$cellphone <- as.factor(new_df$cellphone)
new_df$streetcity <- as.factor(new_df$streetcity)
new_df$streetzip <- as.factor(new_df$streetzip)
new_df$County <- as.factor(new_df$County)
new_df$income_source <- as.factor(new_df$income_source)
new_df$employer <- as.factor(new_df$employer)
new_df$referenceperson <- as.factor(new_df$referenceperson)
new_df$incomelevel <- as.factor(new_df$incomelevel)
new_df$carsinhh <- as.factor(new_df$carsinhh)

new_df$status_code <- as.factor(new_df$status_code)
new_df$purpose <- as.factor(new_df$purpose)

#Dropping the 'active' Factor
new_df$status_code <- droplevels(new_df$status_code)
new_df$incomelevel <- droplevels(new_df$incomelevel)
str(new_df)
```

```{r}
#Validation Data Set
val <- df[1:9, ]
val %>% View

#Training Data Set
train <- df[10:130,]
train %>% View

#Testing Data Set
test <- df[131:nrow(df),]
test %>% View
```

```{r}
#Validation Data Set
nval <- new_df[1:9, ]
nval %>% View

#Training Data Set
ntrain <- new_df[10:130,]
ntrain %>% View

#Testing Data Set
ntest <- new_df[131:nrow(new_df),]
ntest %>% View
```


```{r}
#CLASSIFICATION Decision Tree
#install.packages('tree')
library(tree)

#MODEL NUMBER 1 - ALL VARIABLES
model = tree(status_code ~ ., 
             na.action = na.pass, 
             method = "class", 
             split = c("deviance", "gini"),
             data = train)
summary(model)
```

```{r}
#Variables Used in Decision Tree
summary(model)$used
```

```{r}
#Variables Not Used in Decision Tree
names(train)[which(!(names(train) %in% summary(model)$used))]
```

```{r}
#Plotting the Decision Tree
plot(model)
text(model)
```

```{r}
#Confusion Matrix
model_pred = predict(model, train, type = "class")
table(predicted = model_pred, actual = train$status_code)
```

```{r}
#Pruned Decision Tree
prune = prune.misclass(model, best = 12)
summary(prune)
```

```{r}
plot(prune)
text(prune, pretty = 0)
title(main = "Pruned Classification Tree")
```

```{r}
#Testing the Decision Tree
pred <- predict(model, test) 
pred
```

```{r}
#Feature Selection
control <- trainControl(method="repeatedcv", number=10, repeats=3)
model <- train(status_code~., 
               data=train, 
               method="lvq", 
               preProcess="scale", 
               trControl=control, 
               na.action = na.omit)

importance <- varImp(model, scale=FALSE)
print(importance)
plot(importance)
```
    
```{r}

#Model 2 - First Feature Selection 
model2 = tree(status_code ~ amount_approved + employer + streetzip + income_source + 
                incomeamt + incomelevel + purpose + referenceperson, 
             na.action = na.pass, 
             method = "class", 
             split = c("deviance", "gini"),
             data = train)
summary(model2)
#save(model2,file = 'model.RData')
```

```{r}
#Plotting the Decision Tree
plot(model2)
text(model2)
```
```{r}
#Pruned Decision Tree
prune2 = prune.misclass(model2, best = 6)
summary(prune2)

plot(prune2)
text(prune2, pretty = 0)
title(main = "Pruned Classification Tree")
```
```{r}
model_pred = predict(model2, train, type = "class")
table(predicted = model_pred, actual = train$status_code)
```

```{r}
#Model 3 - Second Feature Selection
model3 = tree(status_code ~ amount_approved + amountDue + employer + age + 
                streetzip + incomeamt + income_source + sex + incomelevel + referenceperson + purpose, 
             na.action = na.pass, 
             method = "class", 
             split = c("deviance", "gini"),
             data = train)
summary(model3)

model_pred = predict(model3, train, type = "class")
table(predicted = model_pred, actual = train$status_code)
```
```{r}
#Model 4 - Charged Off Feature Selection
model4 = tree(status_code ~ amount_approved + amountDue + age + 
                streetzip + employer + income_source + referenceperson, 
             na.action = na.pass, 
             method = "class", 
             split = c("deviance", "gini"),
             data = train)
summary(model4)

model_pred = predict(model4, train, type = "class")
table(predicted = model_pred, actual = train$status_code)
```

```{r}
#Model 5 - Paid in Full Feature Selection
model5 = tree(status_code ~ amount_approved + amountDue + employer + streetzip + age,
             na.action = na.pass, 
             method = "class", 
             split = c("deviance", "gini"),
             data = train)
summary(model5)

model_pred = predict(model5, train, type = "class")
table(predicted = model_pred, actual = train$status_code)
```
```{r}
#Model 6 - Paid in Full Feature Selection
model6 = tree(status_code ~ employer + amount_approved + streetzip + incomeamt,
             na.action = na.pass, 
             method = "class", 
             split = c("deviance", "gini"),
             data = train)
summary(model6)

model_pred = predict(model6, train, type = "class")
table(predicted = model_pred, actual = train$status_code)
```

```{r}
#Model 7 - Adjusted PIF and Refinanced
model7 = tree(status_code ~ ., 
             na.action = na.pass, 
             method = "class", 
             split = c("deviance", "gini"),
             data = ntrain)
summary(model7)

model_pred = predict(model7, ntrain, type = "class")
table(predicted = model_pred, actual = ntrain$status_code)
```
```{r}
#Feature Selection
control <- trainControl(method="repeatedcv", number=10, repeats=3)
model <- train(status_code~., 
               data=ntrain, 
               method="lvq", 
               preProcess="scale", 
               trControl=control, 
               na.action = na.omit)

importance <- varImp(model, scale=FALSE)
print(importance)
plot(importance)
```

