---
title: "Predatory Lending"
author: "BetterFi • Datalab"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#FAFBFE"
      fg: "#d4c5c5" 
      primary: "#ad4944"
      navbar-bg: "#DE9D49"
      base_font: 
        google: Prompt
      heading_font:
        google: Helvetica
      code_font:
        google: 
          family: sans_serif
          local: false
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(leaflet)
library(leaflet.extras)
library(gsheet)
library(rgdal)
library(raster)
library(RColorBrewer)
library(forcats)
library(lubridate)
library(sf)
library(htmltools)

```

```{r df, include = FALSE}
# reading in TN county polygon data
tncounty<- shapefile('/Users/elizabethmorris/Desktop/Datalab 2022/betterfi/TN_counties/TN_counties')
tncounty<- spTransform(tncounty, CRS("+init=epsg:4326"))

# selecting counties in area
counties <- c('Hamilton', 'Marion', 'Franklin', 'Coffee', 'Grundy')

boundaries <- tncounty[tncounty$NAME %in% counties,]

# reading in map loan data from g sheet
maploan<- read_csv('maploan.csv')

```


```{r icons, echo = FALSE}

paldata<-maploan %>% group_by(county, countyincome, countypop) %>% summarise(total = n())

mergemap <- merge(boundaries, paldata,  by.x = 'NAME', by.y = 'county')


pal <- colorNumeric(
    palette = "Reds",
    domain = paldata$total)
# Loaing in awesome icon, its a bit finicky but works
cash <- makeAwesomeIcon(
  icon = "money bill",
  iconColor = "#FAFBFE",
  markerColor ="red",
  library = "fa")

# making popup labels
labels <- sprintf(
  "<strong>%s</strong><br/>median income: $%g <br/>population: %g",
  mergemap$NAMELSAD, mergemap$countyincome, mergemap$countypop
) %>% lapply(htmltools::HTML)


```


 {data-orientation=rows}
=======================================

Sidebar {.sidebar} 
---------------------------------------
###

<font size="3" color = "#853801"> This map shows potential predatory lending locations that offer payday, title, flex, and installment loan services. All of these stores have interest rates that can range up to *460%* annual percentage rate. If a store's APR is available to the public, when you hover over the location, it shows how high the store may charge interest on your loan.</font>

<font size="3" color = "#d66d1c"> BetterFi is different. We have an APR of 24% and offer a variety of services to help get your finances back on track. So avoid these places, come to BetterFi! </font>

Row
---------------------------------------
###

```{r}
renderValueBox({
  valueBox("Number of Payday Lending Locations in TN",
           value = "~1,023",
           icon = "fa-building")
})
```

###

```{r}
renderValueBox({
  valueBox("Number of McDonald's in TN",
           value = "285",
          icon = "fa-user")
})
```

Row
---------------------------------------
### Map 

```{r map, echo = FALSE}
renderLeaflet({
leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addAwesomeMarkers(data = maploan,
                    label = ~maploan$apr, 
                    icon = cash)%>%
  addPolygons(data = mergemap,
              color = "orange",
              fillColor = ~pal(total),
              fillOpacity = .6,
              weight = 2,
              opacity = .9,
              label = ~labels,
              labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "12px", 
    direction = "auto"),
              highlightOptions = highlightOptions(
                color = "#f0e771", bringToFront = TRUE )) %>%
   addControlGPS(options = gpsOptions(
                position = "topleft", activate = TRUE,
                autoCenter = TRUE, maxZoom = 200,
                setView = TRUE)) %>% 
    addLegend(pal = pal,
        values = paldata$total,
        opacity = 0.7,
        title = htmltools::HTML("Payday Loan <br/>Locations"),
        position = "bottomright")
})
```

